# Generated by Django 5.2.6 on 2025-10-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chapters/'),
        ),
    ]
