# Generated by Django 5.2.6 on 2025-11-04 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_chapter_course_alter_course_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='department',
            new_name='category',
        ),
    ]
